spring:
  application:
    name: traveldiary-login

app:
  jwt:
    private-key: classpath:keys/traveldiary-private_pkcs8.pem
    public-key: classpath:keys/traveldiary-public.pem
    ttl:
      access-token-ttl: 1h
      refresh-token-ttl: 14d

  oauth:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
