spring:
  application:
    name: traveldiary-login
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: update   # 개발용 스키마 자동 생성/갱신 (운영은 Flyway/Liquibase 권장)
    show-sql: true

app:
  jwt:
    private-key: classpath:keys/traveldiary-private_pkcs8.pem
    public-key: classpath:keys/traveldiary-public.pem
    ttl:
      access-token-ttl: 1h
      refresh-token-ttl: 14d

  oauth:
    google:
      client-id: ${GOOGLE_CLIENT_ID:626396611666-o9s8esbg30bq285smsm0btlge8r5bggm.apps.googleusercontent.com}
